#!/bin/bash
DIR=`dirname $0`
PWD=`pwd`
. /etc/restatemachine/shell_helpers.inc

INPUT=`cat`

CURRENT_DIR="/opt/puppetmaster-gui/statemachines/provision_server"
HOSTNAME=`echo "$INPUT" | jq -r '.hostname'`
USERNAME=`echo "$INPUT" | jq -r '.username'`
PASSWORD=`echo "$INPUT" | jq -r '.password'`
NEW_PASSWORD=`echo "$INPUT" | jq -r '.new_password'`
KEY=`echo "$INPUT" | jq -r '.key'`
OS=`echo "$INPUT" | jq -r '.os'`
ENVIRONMENT=`echo "$INPUT" | jq -r '.environment'`
ROLES=`echo "$INPUT" | jq -r '.roles'`

#HOSTNAME="ec2-52-50-198-165.eu-west-1.compute.amazonaws.com"
PUPPETMASTER=`hostname -f`
#USERNAME="ubuntu"
#PASSWORD=""
#KEY="/root/amazon.key"
#OS="ubuntu"

Error () {
	ERROR_MESSAGE=`echo "$1" | sed ':a;N;$!ba;s/\n/ /g'`
        echo -n "$INPUT"
        restatemachine_transition_to "setup_puppet"
        restatemachine_transition_after_seconds "60"
        restatemachine_status_message "$ERROR_MESSAGE"
        exit 0
}

if [ "$OS" == "linux" ] || [ "$OS" == "ubuntu" ];  then
        if [ -n "$KEY" ]; then
		SSH_COMMAND="ssh -o ConnectTimeout=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i "$KEY" "$USERNAME"@"$HOSTNAME" "
        else
		SSH_COMMAND="sudo sshpass -p "$PASSWORD" ssh -o ConnectTimeout=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$USERNAME"@"$HOSTNAME" "
        fi

        INSTALL_PUPPET=`$SSH_COMMAND 2>&1 'sudo bash -s' < "$CURRENT_DIR"/scripts/install_puppet.sh "$PUPPETMASTER" "$ENVIRONMENT"`
        if [ "$?" != "0" ]; then
		Error "failed|Could not login server might be rebooting|${INSTALL_PUPPET}"
        	#Error "{\"status\":\"failed\", \"message\":\"Could not login to the server via SSH with the provided key $INSTALL_PUPPET \"}"
        fi
	RUN_PUPPET=`$SSH_COMMAND 2>&1 -q sudo puppet agent --test`
	# Puppet exit codes
	if [ "$?" == "0" ] || [ "$?" == "2" ]; then
		# Provisioning is ok
		OK=1
	else
		Error "pending|installation in progress|$? ${RUN_PUPPET}"
		#Error "{\"status\":\"pending\", \"message\":\"$RUN_PUPPET\"}"
	fi

	#0: The run succeeded with no changes or failures; the system was already in the desired state.
	#1: The run failed, or wasn't attempted due to another run already in progress.
	#2: The run succeeded, and some resources were changed.
	#4: The run succeeded, and some resources failed.
	#6: The run succeeded, and included both changes and failures.
elif [ "$OS" == "windows" ]; then
	INSTALL_PUPPET=`"$CURRENT_DIR"/winrm/install_puppet.py --host="$HOSTNAME" --username="$USERNAME" --password="$PASSWORD" --environment="$ENVIRONMENT" --puppetmaster="$PUPPETMASTER" --roles="$ROLES"`
	if [ "$?" != "0" ]; then
		#Error "{\"status\":\"pending\", \"message\":\"Failed to install puppet on host. Error: $INSTALL_PUPPET\"}"
		# Try again with alternative credentials
		INSTALL_PUPPET_2=`"$CURRENT_DIR"/winrm/install_puppet.py --host="$HOSTNAME" --username="$USERNAME" --password="$NEW_PASSWORD" --environment="$ENVIRONMENT" --puppetmaster="$PUPPETMASTER" --roles="$ROLES"`
		if [ "$?" != "0" ]; then
			Error "pending|installation in progress|Password ${INSTALL_PUPPET} ------- ${INSTALL_PUPPET_2}"
		fi
	fi
	RUN_PUPPET=`"$CURRENT_DIR"/winrm/run_puppet.py --host="$HOSTNAME" --username="$USERNAME" --password="$PASSWORD" --environment="$ENVIRONMENT" --puppetmaster="$PUPPETMASTER" --roles="$ROLES"`
	if [ "$?" != "0" ]; then
		FOO=$?
		RUN_PUPPET_2=`"$CURRENT_DIR"/winrm/run_puppet.py --host="$HOSTNAME" --username="$USERNAME" --password="$NEW_PASSWORD" --environment="$ENVIRONMENT" --puppetmaster="$PUPPETMASTER" --roles="$ROLES"`
		if [ "$?" != "0" ]; then
			Error "pending|installation in progress| ${FOO} $? ${RUN_PUPPET} ------- ${RUN_PUPPET_2}"
		fi
	fi

fi
RAND=`shuf -i 1-10 -n 1`
echo -n "$INPUT"
restatemachine_transition_to "stop"
restatemachine_transition_after_seconds "$RAND"
restatemachine_status_message "done|Provisioning complete|"
