#!/bin/bash
DIR=`dirname $0`
. /etc/restatemachine/shell_helpers.inc

INPUT=`cat`
Retry () {
        echo -n "$INPUT"
        restatemachine_transition_to "fetch_admin_password"
        restatemachine_transition_after_seconds "10"
        restatemachine_status_message "{\"status\":\"pending\", \"message\":\"Waiting for password\"}"
        exit 0
}

INSTANCE_ID=`echo "$INPUT" | jq -r '.instance_id'`
KEY=`echo "$INPUT" | jq -r '.key_name'`

PASSWORD=`aws ec2 get-password-data --instance-id="$INSTANCE_ID" --priv-launch-key=/root/amazon.key | jq -r .PasswordData`
if [ "$PASSWORD" == "" ]; then
        Retry
else
        INPUT=`echo -n "$INPUT" | jq '.password = "'"$PASSWORD"'"'`
        echo -n "$INPUT"
        restatemachine_transition_to "configure_server"
        restatemachine_transition_after_seconds "0"
        restatemachine_status_message "{\"status\":\"pending\", \"message\":\"Configuring server\"}"
fi
