#!/bin/bash
DIR=`dirname $0`
. /etc/restatemachine/shell_helpers.inc

INPUT=`cat`
Error () {
        echo -n "$INPUT"
        restatemachine_transition_to "test_root"
        restatemachine_transition_after_seconds "60"
        restatemachine_status_message "$1"
        exit 0
}

HOSTNAME=`echo "$INPUT" | jq -r '.hostname'`
USERNAME=`echo "$INPUT" | jq -r '.username'`
PASSWORD=`echo "$INPUT" | jq -r '.password'`
KEY=`echo "$INPUT" | jq -r '.key'`
OS=`echo "$INPUT" | jq -r '.os'`

if [ "$OS" == "linux" ] || [ "$OS" == "ubuntu" ];  then
	if [ -n "$KEY" ]; then
		ROOT=`ssh -oStrictHostKeyChecking=no -i "$KEY" "$USERNAME"@"$HOSTNAME" -q 'sudo id -u 2>&1'`
		if [ "$?" != "0" ]; then
			Error "{\"status\":\"failed\", \"message\":\"Could not verify root privileges for user\"}"
		fi
	else
		ROOT=`sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no "$USERNAME"@"$HOSTNAME" -q 'sudo id -u'`
		if [ "$?" != "0" ]; then
			Error "{\"status\":\"failed\", \"message\":\"Could not verify root privileges for user\"}"
		fi
	fi
	if [ "$ROOT" != "0" ]; then
		Error "{\"status\":\"failed\", \"message\":\"$USERNAME is lacking root privileges\"}"
	fi
elif [ "$OS" == "windows" ]; then
	ADMINISTRATOR=`./etc/restatemachine/statemachines/pre_flight_checks/winrm/test_administrator.py --host="$HOSTNAME" --username="$USERNAME" --password="$PASSWORD"`
	if [ "$?" != "0" ]; then
		Error "$ADMINISTRATOR"
	fi
else
	Error "{\"status\":\"failed\", \"message\":\"Unknown operating system $OS \"}"
fi


echo -n "$INPUT"
restatemachine_transition_to "test_repo_access"
restatemachine_transition_after_seconds "0"
restatemachine_status_message "{\"status\":\"pending\", \"message\":\"Testing repository access\"}"
